### ISSUE TITLE
Make integration for hassio, not just home-assistant

### ISSUE THREAD

**Issue by olekenneth** [olekenneth/pyXcomfort#2]
Create a add-on for hassio.

## How to

https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html
https://github.com/hassio-addons

**Comment by JSmurf** [comment]
I believe I still have hassio installed on something at home. I can try to take a stab at this.

**Comment by olekenneth** [comment]
Great! I haven't hassio up, so if you do, that's super.

**Comment by JSmurf** [comment]
I had it installed on a Pi I got from a coworker, and got it set up, but didn't have much to really use it with, so when I moved it got put in a box, and is probably still floating around somewhere. 

Hopefully as early as tomorrow night I can dig it out, and then I can start figuring out how to get this together.

**Comment by olekenneth** [comment]
@JSmurf Need any help? Only today and tomorrow left

**Comment by magnulf** [comment]
Hey,
Any plans on making it a proper Hassio addon?

**Comment by olekenneth** [comment]
Actually I got a working version, just haven't had the time to commit it

**Comment by magnulf** [comment]
@olekenneth - if you want, I can be your beta-tester.  :-)

**Comment by magnulf** [comment]
Also - I'm willing to help in any way I can, of course. :-)

**Comment by magnulf** [comment]
@olekenneth I'm very sorry to ping and bother you, but now I'm ready to get the final piece of the puzzle ready - and test it. If you commit what you've got running already, then I can try to take it from there. :-)

**Comment by olekenneth** [comment]
Try this: https://github.com/olekenneth/hassio-addons

**Comment by olekenneth** [comment]
@magnulf did you test it?

**Comment by magnulf** [comment]
@olekenneth Yes I did. Just created a pull-request for you. :-)

You rock!
