### ISSUE TITLE
Add MQTT integration

### ISSUE THREAD

**Issue by olekenneth** [olekenneth/pyXcomfort#3]
Please help me with adding a MQTT integration to pyXcomfort

**Comment by kedMertens** [comment]
Hi, @olekenneth !
I would like to contribute by working on the issue.
I have experience with MQTT. Do you have in mind some libraries?
I could investigate the issue and we could discuss options.
What do you think?

**Comment by olekenneth** [comment]
Awesome! I guess paho is used a lot. So that probably a good choice.

**Comment by kedMertens** [comment]
> Awesome! I guess paho is used a lot. So that probably a good choice.

I'm totally agree with you. Should I open PR to start working on that?

**Comment by olekenneth** [comment]
I guess you can start by forking it and add some code, then add a PR, when you have something useful with tests

**Comment by kedMertens** [comment]
> I guess you can start by forking it and add some code, then add a PR, when you have something useful with tests

Got it! Could you please mark that issue with Work In Progress (WIP) tag?

**Comment by kedMertens** [comment]
@olekenneth, could you please clarify where MQTT protocol has to be applied? 
Is it correct that now data from light bulb goes through serial protocol with help of RS-232?

**Comment by olekenneth** [comment]
Yes. That's correct. I assume you don't have Xcomfort or the RS-232-adapter, so you need to use the tests as way of implementing this. I have tests that will trigger the callbacks

**Comment by kedMertens** [comment]
Thank you, got it!
Unfortunately, I don't have one.
I found [datasheets and documentation](http://www.eaton.eu/Europe/Electrical/ProductsServices/Residential/xComfort-RFSmartHomeSolutions/index.htm?wtredirect=www.eaton.eu/xcomfort#tabs-11).
I keep working.

**Comment by kedMertens** [comment]
@olekenneth, I need some help. 
Could you please describe in details the Xcomfort set? 
With pyXcomfort library it is possible to access data directly from Home Controller device or there is smart light device?
And by integrating MQTT protocol, where the application should be deployed?

**Comment by olekenneth** [comment]
The RS-232 interface is connected to the computer. This have a radio to communicate directly with lights (over 868Mhz). 

We send data to the interface which contains instructions to a specific light to turn on/dim etc. 
You can see in the tests how this looks. 

The task to implement MQTT should only need to use the callbacks and forward the information obtained to the MQTT stream.

**Comment by kedMertens** [comment]
> 
> 
> The RS-232 interface is connected to the computer. This have a radio to communicate directly with lights (over 868Mhz).
> 
> We send data to the interface which contains instructions to a specific light to turn on/dim etc.
> You can see in the tests how this looks.
> 
> The task to implement MQTT should only need to use the callbacks and forward the information obtained to the MQTT stream.

Thank you for clarification.
Sorry, I was out these days. Will work on the issue this weekends.

**Comment by olekenneth** [comment]
Implemented in the hassio/supervised-addon
