### ISSUE TITLE
Adopt Black code formatter

### ISSUE THREAD

**Issue by olekenneth** [olekenneth/pyXcomfort#5]
I created my own lint config that follows a style I like, but instead of maintaining that I want to adopt Black code formatter. 

See https://black.readthedocs.io/en/stable for more information.

**Comment by simonbcodes** [comment]
I'm assuming that we would want to set up version control integration? That would require updating the requirements.txt to include both black and pre-commit. We would also need to include a .pre-commit-config.yaml that hooks into Black itself. I'd be happy to work on it if you'd like.

https://black.readthedocs.io/en/stable/version_control_integration.html

**Comment by olekenneth** [comment]
Sounds good. Let's add pre-commit
